services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: password
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/data
    environment:
      # Admin Token https://password.nireus.cc/admin
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=123456
      - WEBSOCKET_ENABLED=true
      - LOG_LEVEL=info
      - DOMAIN=https://password.example.org